jms_serializer:
    handlers:
        datetime:
            default_format: 'd/m/y'
            default_time_format: 'UTC'
    metadata:
        auto_detection: true
        directories:
            DominModel:
              namespace_prefix: Domanin\Model
              path: '%kernel.root_dir%/Resources/Infrastructure/Serializer/JMS'